### PR TITLE
Update babel dependencies

### PR DESCRIPTION
**Pull request by gcallaghan**

### CODE REVIEW

**Comment by kof** [comment]
merged

**Comment by kof** [comment]
hey @gcallaghan how are you? I was hoping to get more of this pull requests for other repos)))

**Comment by gcallaghan** [comment]
what's left? js-extend and js-default-unit?

**Comment by kof** [comment]
jss, jss-extend, jss-default-unit, react-jss and examples)

**Comment by kof** [comment]
maybe we need a single repo with the setup for all this stuff inside, updating all of them is a big overhead.

**Comment by gcallaghan** [comment]
Ok, there is already a PR for JSS, https://github.com/jsstyles/jss/pull/188. I'll get a few more in today.

**Pull request merged**
