### PR TITLE
Array support for jss-camel-case

### PR DESCRIPTION
**Pull request by mindjuice**
Add support for rules like @font-face, which can have multiple styles
in an array.

This was brought up in #jss/199

### CODE REVIEW

**Comment by kof** [comment]
looks good, merged, will publish later all together.

**Comment by mindjuice** [comment]
Looks like 1.1.0 didn't get released properly.  The latest available version is still 1.0.2.

**Comment by kof** [comment]
oh yes, forgot this one.

**Comment by kof** [comment]
published now

**Pull request merged**
